### ISSUE TITLE
Calibre 3.39.1 portable fails to install (error about less than 59 characters)

### ISSUE THREAD

**Issue by PhoenixRe32** [lukesampson/scoop-extras#1765]
When trying to install calibre (portable, version 3.39.1 I get an error saying
![image](https://user-images.githubusercontent.com/35810509/53280810-90396700-3716-11e9-8e33-391ddae6278b.png)

Not sure if it's some kind of limit with the portable version. 
Calibre-normal seems to be fine

**Comment by r15ch13** [comment]
Unfortunately, this is a problem with calibre.
https://github.com/kovidgoyal/calibre/blob/c81ffa6d1a7b6740203b5a99b807a65b86ea6040/src/calibre/gui2/main.py#L90-L94

You can install [calibre-normal](https://github.com/lukesampson/scoop-extras/blob/master/bucket/calibre-normal.json) which will work but save its data in `%AppData%`

**Comment by PhoenixRe32** [comment]
Yeah, I looked it a bit more after that and came to the same conclusion.
Installed normal after that. Thanks

Best Regards,



Andreas Andreou
Software Developer
Τα τρία Τ της επιτυχίας: Ταλέντο, Τόλμη, Τύχη.
M: +44 (0) 7462 887 207

**Comment by rasa** [comment]
Wouldn’t addding `Calibre Portable` to the `extract_dir` [here](
https://github.com/lukesampson/scoop-extras/blob/9b6d3a54789432ca69e49a96cf2b5219f23f5b72/bucket/calibre-normal.json#L10) fix this?

**Comment by hsiktas** [comment]
This is still happening to me when I try to install calibre-portable-installer-3.40.1.exe. I guess this is not fixed.

**Comment by Ash258** [comment]
There is nothing Scoop manifest could do about it. This is limitation of Calibre itself. Write to developers to change it.

**Comment by hsiktas** [comment]
Hi,
I followed @r15ch13's advice and switched over to `calibre-normal`. The issue is gone now. 😀

**Comment by juanjosegarciaripoll** [comment]
Why is this closed? This is a problem. The solution would be either to leave it open, or to remove the recipe altogether.

**Comment by 7wells** [comment]
Hi, I (still) have the same problem. Maybe removing the portable version of Calibre from this bucket is better than letting users run into this problem and repeating the same comments (like me, blush). Or does it work for somebody?

See there:
https://github.com/lukesampson/scoop-extras/issues/2535

**Comment by nuno-andre** [comment]
Just replace the `installer.args` in the manifest with

```powershell
"installer": {
    "script": [
        "start \"$dir\\calibre-portable-installer-$version.exe\" @(\"$dir\") -wait",
        "mv \"$dir\\Calibre Portable\\**\" \"$dir\"",
        "rm \"$dir\\Calibre Portable\""
    ]
},
```

and remove all the `Calibre Portable\\` strings, e.g.

`"Calibre Portable\\Calibre\\calibre-customize.exe"` &rarr; `"Calibre\\calibre-customize.exe"`

And that's all as long as installed in the default folder (since the username shouldn't be as long as the 22 characters that are now left over). Otherwise, YMMV.

**Comment by harvastum** [comment]
@nuno-andre 
Isn't the manifest going to be overwritten the next time Scoop updates, causing the problem to return on Calibre update? I think that the manifest should be fixed in the bucket.

**Comment by rashil2000** [comment]
Can you make a PR for the fix?

**Comment by agatakotecka** [comment]
Why this is still not solved? Who are you hiring for inept developer?
21st century we have, and some stupid limitation of 59 characters !
